---
 - name: correct the ssh config for the machines
   hosts: web
   become: True
   become_method: sudo

   tasks: 
     - name: Step 1.0 ping remote node
       ping:

     - name: Step 1.1 Upgrade all packages to the latest version
       apt:  
         upgrade: dist


     - name: Step 1.2 Install apache2
       apt:  
         pkg: apache2
         state: present
         update_cache: true   

       
     - name: Step 1.3 test_apache2_config
       shell: "apache2ctl configtest"
       register: teststage1
       
     - name: Step 1.4 Last message for apache restarted
       debug: msg=" {{ teststage1.stderr_lines  }} RC= {{ teststage1.rc  }}"
       
     - name: Step 1.5 Replace ServerName with localip
       lineinfile: 
         path: /etc/apache2/apache2.conf
         regexp: '^ServerName'
         line: 'ServerName {{ inventory_hostname }}'

     - name: Step 1.6 Restart apache2
       service: 
         name: apache2
         state: restarted


     - name: Step 1.7 Last message for apache restarted
       debug: msg=" {{ teststage1.stderr_lines  }} RC= {{ teststage1.rc  }}"
       
       

     - name: Step 1.8 Install curl
       apt:  
         pkg: curl
         state: present
         update_cache: true 




     - name: Step 1.9Test Local url via uri
       uri:
         url: http://localhost
#         return_content: yes
#       register: webpage
       
#     - name: Fail if AWESOME is not in the page content
#       fail:
#       when: "'AWESOME' in webpage.content"



     - name: Step 3 Install PHP
       apt:
         pkg: php 
         state: present
         update_cache: true

     - name: Step 3.1 Install libapache2-mod-php
       apt:
         pkg: libapache2-mod-php 
         state: present
         update_cache: true

     - name: Step 3.2 Install php-mcrypt 
       apt:
         pkg: php-mcrypt 
         state: present
         update_cache: true
         




     - name: Step 3.3 Install  php-mysql 
       apt:
         pkg: php-mysql 
         state: present
         update_cache: true
         



     - name: Step 3.4 chnage index.php  priority
       lineinfile: 
         path: /etc/apache2/mods-enabled/dir.conf
         regexp: '    DirectoryIndex index.html index.cgi index.pl index.php index.xhtml index.htm'
         line: '    DirectoryIndex index.php index.html index.cgi index.pl index.xhtml index.htm'

     - name: Step 3.5 Restart apache2
       service: 
         name: apache2
         state: restarted
         
         
         
     - name: Step 3.6 Status apache2
       service: 
         name: apache2
         state: started
         

     - name: Step 3.7 Status php-cli
       apt:
         pkg: php-cli 
         state: present
         update_cache: true

     - name: Step 4.0 Install  mysql-init
       script: /home/ejhakun/emptydir/ansible/playbooks/bin/install_mysql.sh
       when: inventory_hostname  == 'machine3'
       

